package com.perscholas.homeinsurance.dao;

import java.io.IOException; 

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import com.perscholas.homeinsurance.interfaces.UserDAOI;
import com.perscholas.homeinsurance.models.User;

public class UserDAO implements UserDAOI
{
	/**Returns the user Id  autogenerated by the database during insertion.
	 *@param user Represents an initialized User Object to be inserted into the database.
	 *@return Returns the user identification number.
	 *@throws SQLException
	 *@throws ClassNotFoundException
	 *@throws IOException
	*/
	@Override
	public Integer registerUser(User user) throws SQLException, ClassNotFoundException, IOException 
	{
		//Declare all variables
		//Create Connection, PreparedStatement, and ResultSet Objects and
		//initialize to null. Create an OracleConnection Object with Java default Constructor.
		Connection conn = null;			
		PreparedStatement stmt = null;	
		ResultSet rs = null;			
		OracleConnection orcl= new OracleConnection();	
		
		// Assign query statement (SQL) to String variable
		String insertString = "insert into users (user_name, password, admin_role) values (?,?,?)";
		
		//Assign column id value to String array for auto generated keys
		String[] COL = {"user_id"};
		int ID = -1;
	    
		//Assign value to Connection Object using getConnection
		//method from OracleConnection Class.
	    conn = orcl.getConnection();  
		System.out.println("DATABASE CONNECTION ESTABLISHED");
	   
	    try
		{
	    	//Initialize Statement Object with passing of query and column id 
	    	//Initialize Statement Object with column index and value to be inserted into the column
	        stmt = conn.prepareStatement(insertString, COL);
	        
	        stmt.setString(1, user.getUserName());
	        stmt.setString(2, user.getPassword());
	        stmt.setString(3, user.getAdminRole());
	        
	        //Execute query
	        stmt.executeUpdate();
	       
	        //Assign returned values to ResultSet Object.
	        rs = stmt.getGeneratedKeys();
	        if(rs != null && rs.next()) 
	        {
	            ID = rs.getInt(1);
	            user.setUserId(ID);
	            System.out.println("The user has been registered as USER ID#: "+ID);
	        }
	    }
	    catch (SQLException e)
		{
			System.out.println("Error: " + e.getMessage());
		}
		finally
		{
			//Close all database access Objects
			if (rs != null) 
			{
				rs.close();
			}
			if (stmt != null) 
			{
				stmt.close();
			}
			if (conn != null) 
			{
				conn.close();
			}
		}
	    
		return ID;
	}
	
	/**Returns a List containing a User Object retrieved from the database based on the user identification number passed.
	 *@param user_id Represents the user identification number.
	 *@return Returns List containing User Object matching passed user_id variable.
	 *@throws SQLException
	 *@throws ClassNotFoundException
	 *@throws IOException
	*/
	@Override
	public User getUserByUserId(int user_id) throws ClassNotFoundException, IOException, SQLException
	{
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		OracleConnection orcl = new OracleConnection();
		
		//Create List Object to return, and User Object to to store in list from database.
		
		User user = null;
		
		String fetchString = "SELECT users.user_Id, users.user_name, users.password,"+
							  "users.admin_Role FROM users WHERE users.user_Id = ?";
		try
		{
			conn = orcl.getConnection();
			stmt = conn.prepareStatement(fetchString);
			stmt.setInt(1, user_id);
			rs = stmt.executeQuery();
			
			
			while(rs.next())
			{
				user = new User(rs.getString(2), rs.getString(3), rs.getString(4));
				user.setUserId(rs.getInt(1));
			}
		}
		catch(SQLException e)
		{
			System.out.println("Error: " + e.getMessage());
		}
		finally
		{
			if (rs != null) 
			{
				rs.close();
			}
			if (stmt != null) 
			{
				stmt.close();
			}
			if (conn != null) 
			{
				conn.close();
			}
		}
		return user;
	}
	
	/**Returns a List containing a User Object retrieved from the database based on the username variable used during login .
	*@param userName Represents the user name of the User Object.
	*@return Returns User Object matching passed username and password variables.
	*@throws SQLException
	*@throws ClassNotFoundException
	*@throws IOException
	*/
	@Override
	public User getUserByUsername(String userName) throws ClassNotFoundException, IOException, SQLException
	{
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		OracleConnection orcl = new OracleConnection();
	
		//Create List Object to return, and User Object to to store in list from database.
		List<User> userList = null;
		User user = null;
	
		String fetchString = "SELECT * FROM users WHERE user_name = ?";//Since username is unique, only one user can be generated
		try
		{
			conn = orcl.getConnection();
			stmt = conn.prepareStatement(fetchString);
			stmt.setString(1, userName);
			rs = stmt.executeQuery();
			userList = new ArrayList<User>();
		
			while(rs.next())
			{
				user = new User(rs.getString(2), rs.getString(3), rs.getString(4));
				user.setUserId(rs.getInt(1));
				userList.add(user);
			}
		}
		catch(SQLException e)
		{
			System.out.println("Error: " + e.getMessage());
		}
		finally
		{
			if (rs != null) 
			{
				rs.close();
			}
			if (stmt != null) 
			{
				stmt.close();
			}
			if (conn != null) 
			{
				conn.close();
			}
		}
		return user;
	}

/**Returns a List containing a User Object retrieved from the database based on the username variable used during login .
*@param password Represents the password of the User Object.
*@return Returns User Object matching passed password variable.
*@throws SQLException
*@throws ClassNotFoundException
*@throws IOException
*/
@Override
public User getUserByPassword(String password) throws ClassNotFoundException, IOException, SQLException
{
	Connection conn = null;
	PreparedStatement stmt = null;
	ResultSet rs = null;
	OracleConnection orcl = new OracleConnection();

	//Create List Object to return, and User Object to to store in list from database.
	List<User> userList = null;
	User user = null;

	String fetchString = "SELECT * FROM users WHERE password = ?";//Since username is unique, only one user can be generated
	try
	{
		conn = orcl.getConnection();
		stmt = conn.prepareStatement(fetchString);
		stmt.setString(1, password);
		rs = stmt.executeQuery();
		userList = new ArrayList<User>();
	
		while(rs.next())
		{
			user = new User(rs.getString(2), rs.getString(3), rs.getString(4));
			user.setUserId(rs.getInt(1));
			userList.add(user);
		}
	}
	catch(SQLException e)
	{
		System.out.println("Error: " + e.getMessage());
	}
	finally
	{
		if (rs != null) 
		{
			rs.close();
		}
		if (stmt != null) 
		{
			stmt.close();
		}
		if (conn != null) 
		{
			conn.close();
		}
	}
	return user;
}
}